### ISSUE TITLE
New serie with Decklog 

### ISSUE THREAD

**Issue by Akenaide** [ronelm2000/wsmtools#23]
Hello, I got this error with an empty cards.db.

```
PS E:\wsmtools> ./wstools export https://decklog.bushiroad.com/view/FHL4 --with sendtcp,upscaling --out sharex
[17:45:27 INF] [] Starting...
[17:45:28 INF] [] The latest version is: "0.6.0"
[17:45:28 INF] [] The latest version on repository: "v0.6.0"
[17:45:28 INF] [Montage.Weiss.Tools.CLI.ExportVerb] Running...
[17:45:32 INF] [Montage.Weiss.Tools.Impls.Parsers.Deck.DeckLogParser] Parsing ID: "FHL4"
Unhandled exception. Montage.Weiss.Tools.Entities.Exceptions.DeckParsingException: The following serials are missing from the DB:
SBY/W64-026
SBY/W64-032
SBY/W64-052
SBY/W64-057
SBY/W64-078S
SBY/W77-044
SBY/W64-070
SBY/W64-096
SBY/W64-030
SBY/W77-055
SBY/W64-056
SBY/W64-094
SBY/W64-P02
SBY/W64-014
SBY/W64-029
SBY/W64-028
SBY/W64-035
SBY/W64-058
SBY/W77-050
SBY/W64-092
SBY/W64-084
SBY/W64-076
SBY/W77-076
SBY/W77-046
SBY/W64-097
SBY/W64-074
SBY/W64-075
   at Montage.Weiss.Tools.Impls.Parsers.Deck.DeckLogParser.Parse(String sourceUrlOrFile)
   at Montage.Weiss.Tools.CLI.ExportVerb.Run(IContainer ioc)
   at Montage.Weiss.Tools.Program.<>c__DisplayClass0_0.<<Main>b__2>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Montage.Weiss.Tools.Program.Main(String[] args)
   at Montage.Weiss.Tools.Program.<Main>(String[] args)
```

And if I get informations from encoredeck, images do not load it retry "infinitely".

**Comment by ronelm2000** [comment]
This issue occurs if you have issues with one of the image sources (it defaults to yuyutei which can lag alot if you're coming from Europe). Try parsing manually with `--with skip:yyt` to use DeckLog images exclusively.
```ps
./wstools parse https://www.heartofthecards.com/translations/rascal_does_not_dream_of_bunny_girl_senpai_booster_pack.html --with skip:yyt
```

**Comment by Akenaide** [comment]
I think it's the same error (and yes I'm from France)
```
[22:27:26 INF] [Montage.Weiss.Tools.CLI.ParseVerb] Added to DB: "BFR/S78-111"
[22:27:26 INF] [Montage.Weiss.Tools.Impls.PostProcessors.DeckLogPostProcessor] Found and adding data: ["BFR/S78-112"]
[22:27:26 INF] [Montage.Weiss.Tools.CLI.ParseVerb] Added to DB: "BFR/S78-112"
[22:27:26 INF] [Montage.Weiss.Tools.Impls.PostProcessors.DeckLogPostProcessor] Found and adding data: ["BFR/S78-113"]
[22:27:26 INF] [Montage.Weiss.Tools.CLI.ParseVerb] Added to DB: "BFR/S78-113"
[22:27:26 INF] [Montage.Weiss.Tools.Impls.PostProcessors.DeckLogPostProcessor] Found and adding data: ["BFR/S78-114"]
[22:27:26 INF] [Montage.Weiss.Tools.CLI.ParseVerb] Added to DB: "BFR/S78-114"
[22:27:26 INF] [Montage.Weiss.Tools.Impls.PostProcessors.DeckLogPostProcessor] Found and adding data: ["BFR/S78-P01"]
[22:27:26 INF] [Montage.Weiss.Tools.CLI.ParseVerb] Added to DB: "BFR/S78-P01"
[22:27:26 INF] [Montage.Weiss.Tools.Impls.PostProcessors.DeckLogPostProcessor] Found and adding data: ["BFR/S78-P02"]
[22:27:26 INF] [Montage.Weiss.Tools.CLI.ParseVerb] Added to DB: "BFR/S78-P02"
[22:27:26 INF] [Montage.Weiss.Tools.CLI.ParseVerb] Successfully parsed: "https://www.heartofthecards.com/translations/bofuri-_i_don-t_want_to_get_hurt-_so_i-ll_max_out_my_defense_booster_pack.html"
PS E:\wsmtools> .\wstools.exe export https://decklog.bushiroad.com/view/GJ24
[22:28:22 INF] [] Starting...
[22:28:23 INF] [] The latest version is: "0.6.0"
[22:28:23 INF] [] The latest version on repository: "v0.6.0"
[22:28:23 INF] [Montage.Weiss.Tools.CLI.ExportVerb] Running...
[22:28:27 INF] [Montage.Weiss.Tools.Impls.Parsers.Deck.DeckLogParser] Parsing ID: "GJ24"
Unhandled exception. Montage.Weiss.Tools.Entities.Exceptions.DeckParsingException: The following serials are missing from the DB:
BFR/S78-T08
BFR/S78-T17
   at Montage.Weiss.Tools.Impls.Parsers.Deck.DeckLogParser.Parse(String sourceUrlOrFile)
   at Montage.Weiss.Tools.CLI.ExportVerb.Run(IContainer ioc)
   at Montage.Weiss.Tools.Program.<>c__DisplayClass0_0.<<Main>b__2>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Montage.Weiss.Tools.Program.Main(String[] args)
   at Montage.Weiss.Tools.Program.<Main>(String[] args)
```

**Comment by ronelm2000** [comment]
You are still missing cards from BFR/S78-T which is the TD for Bofuri. Please add them in as well. Thanks~!
```ps
./wstools parse https://heartofthecards.com/translations/bofuri-_i_don-t_want_to_get_hurt-_so_i-ll_max_out_my_defense_trial_deck.html --with skip:yyt
```

**Comment by Akenaide** [comment]
Oh ok, my bad. I was hoping you will use decklog data to initialize.

So the usual use case is to parse hotc before ?

**Comment by ronelm2000** [comment]
> Oh ok, my bad. I was hoping you will use decklog data to initialize.
> 
> So the usual use case is to parse hotc before ?
Unlike with encoredecks, where the set can be implied and parsed automatically, decklog has no card data, only deck data (deck ratios and which serials are used). So manually parsing the related sets is required.

**Comment by Akenaide** [comment]
[https://i.imgur.com/yiYTuQ3.png](url)

They do have card data, but it's not loaded with the deck page. I see you do call an API with encoredeck for card data when you need it, so it should be okay.

**Comment by ronelm2000** [comment]
Closing tickets as part of a cleanup. If you still have issues, feel free to re-open issue.
